bug:
  - "error"
  - "fail"
  - "bug"
  - "crash"

enhancement:
  - "feature"
  - "enhancement"
  - "improvement"

documentation:
  - "doc"
  - "documentation"
  - "readme"

hamster:
  - "automated"
  - "hamster"

issue:
  - "issue"
  - "issues"
  - "bug"

feat:
  - "feature"
  - "feat"
  - "oi"

base:
  - "this"
  - "testing"