bug:
  match:
    - "error"
    - "fail"
    - "bug"
    - "crash"
  description: "Indicates a bug or error in the system."

feature:
  match:
    - "feature"
    - "enhancement"
    - "improvement"
  description: "Suggests a new feature or improvement."

documentation:
  match:
    - "doc"
    - "documentation"
    - "readme"
  description: "Related to documentation updates or changes."

hamster:
  match:
    - 'pet'
    - 'animal'
    - 'automated'
    - 'hamster'
  description: "Thats my hamster."