hamster:
  - automated
  - hamster
  - hamsters
  - hamster-bot
  - hamster-bots
  - Hamster

issue:
  - issue
  - issues
  - bug
  - bugs
  - fix

feat:
  - feature
  - feat
  - 'oi'

base:
  - 'base'
  - 'root'
  - 'this'
  - 'testing'