kind/enhancement:
  - '**/*.js'
  - '**/*.js.map'

kind/typescript:
  - '**/*.ts'
  - '**/*.js' 

kind/ci:
  - '**/*.yml'
  - '.github'

bot/hamster:
  - 'automated'
  - 'hamster'

kind/dotfiles:
  - '**/*.json'
  - '**/*.md'