kind/feature:
  match:
    - '**/*.js'
    - '**/*.js.map'
  description: "Modifies crucial files, an improvement."

kind/typescript:
  match:
    - '**/*.ts'
  description: "Modifies typescript files."

kind/ci:
  match:
    - '**/*.yml'
    - '.github/**/*'
  description: "Modifies ci/cd files."

bot/hamster:
  match:
    - 'pet'
    - 'animal'
    - 'automated'
    - 'hamster'
  description: "Thats my hamster."

kind/dotfiles:
  match:
    - '**/*.yaml'
    - '**/*.json'
    - '**/*.md'
  description: "Modifies dotfiles or configs"

kind/testing:
  match:
    - '**/*.js.map'
    - '**/*.js'
  description: "Testing dept."

kind/docs:
  match:
    - '**/*.md'
    - 'LICENSE'
  description: "Documentation."