kind/enhancement:
  - '/'
  - 'action.yml'
  - '.github'
  - '**/*.yml'

kind/typescript:
  - '**/*.ts'
  - '**/*.js' 

kind/ci:
  - '**/*.yml'
  - '.github'

bot/hamster:
  - 'automated'
  - 'hamster'
