name: auto-label-stuff
description: Super Easy Action to Automatically Apply Labels on Issues and PRs
author: offensive-vk
branding:
  icon: mail
  color: gray-dark
inputs:
  github-token:
    description: "Your GitHub token (PAT or `github.token`). Required to authenticate API requests."
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  create-labels:
    description: "Set to true if the labels does not exist in the repository. If set to false, the action will not create the labels."
    required: false
    default: 'true'
  issue-config:
    description: "Path to file where each label maps to an array of matching strings. File type: .yml, .yaml, .json."
    required: true
  pr-config:
    description: "Path to file for labeling pull request based on file changes. Like labeler.yml in @actions/labeler."
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/offensive-vk/auto-label:latest'