name: CI / Test Action

on: 
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  label:
    name: Label Stuff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Label Issues
      if: github.event_name == 'issues'
      uses: ./
      with:
        create-labels: true
        github-token: ${{ secrets.BOT_TOKEN }}
        issue-config: '.github/issues.yml'

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: ./
      with:
        create-labels: true
        github-token: ${{ secrets.BOT_TOKEN }}
        pr-config: '.github/pr.yml'
  # label_pull_requests:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     pull-requests: write

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4

  #   - name: Label Pull Requests
  #     if: github.event_name == 'pull_request'
  #     uses: actions/labeler@v4
  #     with:
  #       repo-token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}

  # finish_cleanup:
  #   runs-on: ubuntu-latest
  #   needs: [label_issues, label_pull_requests]
  #   steps:
  #   - name: Finish Off & Cleanup
  #     run: echo "Successfully labeled all of the open issues and pull requests."