name: CI / Test Action

on: 
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      number:
        required: true
        type: number
        default: 10
        description: "PR/Issue Number to Run Workflow on."

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  label:
    name: Label Stuff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Label Issues
      if: github.event_name == 'issues'
      uses: ./
      with:
        create-labels: true
        github-token: ${{ secrets.GITHUB_TOKEN || secrets.BOT_TOKEN || secrets.MY_TOKEN  }}
        issue-config: '.github/issues.yml'

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: ./
      with:
        create-labels: true
        github-token: ${{ secrets.GITHUB_TOKEN || secrets.BOT_TOKEN || secrets.MY_TOKEN  }}
        pr-config: '.github/pr.yml'