name: CI / Test Action

on: 
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  label:
    name: Label Stuff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Label Issues
      if: github.event_name == 'issues'
      uses: ./
      with:
        create-labels: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        issue-config: '.github/issues.yml'

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: ./
      with:
        create-labels: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr-config: '.github/pr.yml'