name: CI / Test Action

on: 
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      number:
        required: true
        type: number
        default: "10"
        description: "PR/Issue Number to Run Workflow on."

permissions:
  pull-requests: write
  issues: write

jobs:
  label:
    name: Label Issues and Pull Requests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Validate Config Files
      run: |
        if [[ ! -f .github/issues.yml || ! -f .github/pr.yml ]]; then
          echo "Required config files not found! Please ensure .github/issues.yml and .github/pr.yml exist."
          exit 1
        fi

    - name: Label Issues
      if: github.event_name == 'issues'
      uses: ./
      with:
        debug: false
        create-labels: true
        github-token: ${{ secrets.MY_TOKEN }}
        issue-config: '.github/issues.yml'

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: ./
      with:
        debug: true
        create-labels: true
        github-token: ${{ secrets.MY_TOKEN }}
        pr-config: '.github/pr.yml'

    - name: Debug Event Context
      run: echo "${{ toJSON(github.event) }}"