name: CI / Test Action

on: 
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      number:
        required: true
        type: string
        default: "10"
        description: "PR/Issue Number to Run / Test Workflow on."

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  label:
    name: Label Issues and Pull Requests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Label Issues
      if: github.event_name == 'issues'
      uses: ./
      with:
        debug: true
        create-labels: true
        auth-token: ${{ secrets.GITHUB_TOKEN || github.token }}
        issue-config: '.github/issues.yml'

    - name: Label Pull Requests
      if: github.event_name == 'pull_request'
      uses: ./
      with:
        debug: true
        create-labels: true
        auth-token: ${{ secrets.GITHUB_TOKEN || github.token }}
        pr-config: '.github/pr.yml'
        
    - name: Manual Dispatch
      if: github.event_name == 'workflow_dispatch'
      uses: ./
      with:
        debug: true
        create-labels: true
        github-token: ${{ secrets.MY_PAT || github.token }}
        pr-config: '.github/pr.yml'
        issue-config: '.github/issues.yml'
        number: ${{ github.event.inputs.number }}
        
    - name: Debug Event Context
      run: echo "${{ toJSON(github.event) }}"
